### **Why Do We Need Arrays When We Have Lists?**

1. **Memory Efficiency:**
    - Arrays are more memory-efficient compared to lists. They store elements of the same data type, whereas lists can store elements of mixed types.

        
2. **Type Safety:**
    - Arrays enforce type consistency, meaning all elements must be of the same data type. This reduces the chances of errors when performing mathematical or logical operations.

        
3. **Performance:**
    - For numerical computations, arrays are faster because they avoid the overhead of type checking for each element during operations.

        
4. **Specialized Use Cases:**
    - Arrays are better suited for numerical and scientific computations where all elements share the same type.
    - Libraries like **NumPy** use arrays as their core data structure for matrix operations, numerical integration, and more.

        
5. **List Flexibility vs. Array Specialization:**
    - Lists are more flexible and can store elements of different types.
    - Arrays are specialized for uniform data and are more efficient in computational and memory-heavy tasks.

### **Key Differences Between List and Array**

| **Feature** | **List** | **Array** |
| --- | --- | --- |
| **Type of Data** | Can store mixed data types | Stores data of the same type only |
| **Memory Usage** | More memory overhead | Memory efficient |
| **Performance** | Slower for numerical computations | Faster for numerical computations |
| **Operations** | General-purpose operations | Specialized for numerical operations |
| **Library Dependency** | Built-in | Requires `array` or external libraries like NumPy |

---

### **When to Use Lists**:

1. **Flexibility**: Lists can store elements of **different data types**.
2. **Built-in Methods**: Lists have many built-in methods like `append()`, `pop()`, `sort()`, etc.
3. **Dynamic Sizing**: Lists automatically resize as elements are added or removed.
4. **General Use**: Ideal for most use cases like storing collections of items, stacks, queues, etc.

---

### **When to Use Arrays**:

1. **Performance**: Arrays are faster for **numeric computations** (use libraries like `NumPy`).
2. **Memory Efficiency**: Arrays use less memory for **homogeneous data** (e.g., all integers or floats).
3. **Mathematical Operations**: Arrays support vectorized operations (e.g., element-wise addition).
4. **Specialized Use**: Ideal for scientific computing, machine learning, and large datasets.

### **Explanation of Key Operations**

1. **Access (`O(1)`)**:
    - Python lists are implemented as dynamic arrays, so accessing an element by index is a constant-time operation.
2. **Append (`O(1)`)**:
    - Appending to the end of the list is amortized `O(1)` because Python overallocates memory for the list to reduce the frequency of resizing.
3. **Insert and Delete (`O(n)`)**:
    - Inserting or deleting an element at a specific index requires shifting all subsequent elements, which takes linear time.
4. **Search (`O(n)`)**:
    - Searching for an element by value requires iterating through the list in the worst case.
5. **Sort (`O(n log n)`)**:
    - Python's built-in sorting algorithm (Timsort) has a time complexity of `O(n log n)`.
6. **Slice (`O(k)`)**:
    - Slicing a list creates a new list with the specified elements, so the time complexity depends on the size of the slice.
7. **Extend (`O(k)`)**:
    - Extending a list with another iterable takes time proportional to the length of the iterable being added.

# Arrays

# creation

In [43]:
import array

arr_int=array.array('i',[1,2,3,4,5])


array('i', [1, 2, 3, 4, 5])

In [44]:
type(arr_int)

array.array

In [45]:
import numpy as np

In [46]:
arr_1d=np.array([1,2,3,4,5])

In [47]:
type(arr_1d)

numpy.ndarray

In [52]:
l = [1,2,3,4,4]
arr_1d=np.array(l)
arr_1d

array([1, 2, 3, 4, 4])

In [53]:
type(l)

list

In [57]:
arr_2d=np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [58]:
type(arr_2d)

numpy.ndarray

In [59]:
arr_2d

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

# traversing

In [63]:
for i in arr_1d:
    print(i[4])


[1 2 3 4 5]


In [64]:
for i ,ele in enumerate(arr_1d):
    print(i,ele)


0 [1 2 3 4 5]


# Access

In [1]:
import numpy as np
l = [1,2,3,4,4]
arr_1d=np.array(l)

In [3]:
import array
arr1 = array.array('i', [1, 2, 3, 4, 5])

print(arr1[2]) 


3


In [6]:
print(arr1[4]) 

5


In [11]:
print(arr1[0:5:-2]) 

array('i')


# insertion 

In [14]:

arr1.insert(2, 99)
arr1

array('i', [1, 2, 99, 99, 99, 3, 4, 5])

In [15]:
arr1.append(5)

In [18]:
arr1.extend([34,5,7])

In [19]:
arr1

array('i', [1, 2, 99, 99, 99, 3, 4, 5, 4, 34, 5, 7])

In [20]:
arr1[5] = 2343


In [21]:
arr1

array('i', [1, 2, 99, 99, 99, 2343, 4, 5, 4, 34, 5, 7])

In [24]:
arr1.count(99)

3

In [25]:
len(arr1)

12

In [26]:
arr1.sort()

AttributeError: 'array.array' object has no attribute 'sort'

In [28]:
sorted(arr1, reverse=True)

[2343, 99, 99, 99, 34, 7, 5, 5, 4, 4, 2, 1]

In [29]:
arr1

array('i', [1, 2, 99, 99, 99, 2343, 4, 5, 4, 34, 5, 7])

In [30]:
arr1.reverse()

In [31]:
arr1

array('i', [7, 5, 34, 4, 5, 4, 2343, 99, 99, 99, 2, 1])

In [32]:
arr1[::-1]

array('i', [1, 2, 99, 99, 99, 2343, 4, 5, 4, 34, 5, 7])

In [34]:
991 in arr1

False

In [35]:
arr1*2

array('i', [7, 5, 34, 4, 5, 4, 2343, 99, 99, 99, 2, 1, 7, 5, 34, 4, 5, 4, 2343, 99, 99, 99, 2, 1])

### 1. **Find Duplicates in an Array**

**Problem**: Given an array, find all the elements that appear more than once.

**Approach**:

- Use a set to keep track of elements that have been seen before. If you encounter an element that is already in the set, it's a duplicate.

2. **Find Missing Number in Array**
    - **Problem**: Given an array of n-1 integers in the range of 1 to n, find the missing number.

### 3. **Rotate an Array**

**Problem**: Rotate an array by `k` positions to the right.

**Approach**:

- Use array slicing to achieve the rotation.

### 4. **Merge Two Sorted Arrays**

**Problem**: Given two sorted arrays, merge them into a single sorted array.

**Approach**:

- Use two pointers to iterate through both arrays and add the smaller element to the result array.

### 5. **Find Intersection of Two Arrays**

**Problem**: Find the common elements (intersection) between two arrays.

**Approach**:

- Convert both arrays to sets and find their intersection.

### **6. Move Zeros to the Beginning**

- **Problem**: Move all zeros in an array to the beginning without changing the order of non-zero elements.