In [ ]:
## Array
##creation

import array
arr_int = array.array('i',[1,2,3,4,5])

In [ ]:
type(arr_int)

array.array

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,3,4,5,6])

In [ ]:
type(arr_1d)

numpy.ndarray

In [ ]:
#list
l =[1,2,3,4,56,"Prince"]
arr_1d=np.array(l)
arr_1d

array(['1', '2', '3', '4', '56', 'Prince'], dtype='<U21')

In [ ]:
type(l)

list

In [ ]:
#multidimention array
arr_2d= np.array([[24,2,3,532],[4,67,84,2]])

In [ ]:
type(arr_2d)

numpy.ndarray

In [ ]:
arr_2d

array([[ 24,   2,   3, 532],
       [  4,  67,  84,   2]])

In [ ]:
## traversing - inserting, deleting
## perticular inder par jana


In [ ]:
for i in arr_1d:
   print(i)

1
2
3
4
56
Prince


In [ ]:
for i , ele in enumerate(arr_1d):     ## value and index
    print(i,ele)

0 1
1 2
2 3
3 4
4 56
5 Prince


In [ ]:
## Access the value
arr_1d[4]

np.str_('56')

In [ ]:
print(arr_1d[0:2:-1])

[]


In [ ]:
##insertion - O(n)

arr1=[1,3,5,67,2]
print(arr1)
#inserting
arr1  = np.insert(arr1,3,44)
print(arr1)

[1, 3, 5, 67, 2]
[ 1  3  5 44 67  2]


In [ ]:
arr1 = np.append(arr1,90)
print(arr1)

[ 1  3  5 44 67  2 90]


In [ ]:
arr1 = np.append(arr1, [2, 6, 4]) # Use np.append to add multiple elements to a NumPy array
print(arr1)

[ 1  3  5 44 67  2 90  2  6  4]


In [ ]:
arr1.count(99)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [ ]:
len(arr1)

10

In [ ]:
arr1.sort()

In [ ]:
arr1

array([ 1,  2,  2,  3,  4,  5,  6, 44, 67, 90])

In [ ]:
sorted(arr1,reverse= True) ## sorted stored in new list

[np.int64(90),
 np.int64(67),
 np.int64(44),
 np.int64(6),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(2),
 np.int64(1)]

In [ ]:
arr1

array([ 1,  2,  2,  3,  4,  5,  6, 44, 67, 90])

In [ ]:
# reverse() - reverse the list

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [ ]:
arr1[::-1] ## reverse the array

array([90, 67, 44,  6,  5,  4,  3,  2,  2,  1])

In [ ]:
44 in arr1

True

In [ ]:
arr1*2

array([  2,   4,   4,   6,   8,  10,  12,  88, 134, 180])

In [ ]:
## Reverse an array
#method 1
arr21 = [1,2,3,4,5]
arr21.reverse()


In [ ]:
arr21

[5, 4, 3, 2, 1]

In [ ]:
#2.Method 2
arr21[::-1]

In [ ]:
# Q Find duplicates in array

In [ ]:
def find_duplicates(arr):
    seen = set()
    duplicates = set()

    for num in arr:
        if num in seen:
            duplicates.add(num)
        else:
            seen.add(num)

    return list(duplicates)

# Test
arr = [4, 3, 2, 7, 8, 2, 3, 1]
print(find_duplicates(arr))  # Output: [2, 3]


[2, 3]


In [ ]:
def find_duplicates_sort(arr):
    arr.sort()
    duplicates = []

    for i in range(len(arr) - 1):
        if arr[i] == arr[i + 1] and arr[i] not in duplicates:
            duplicates.append(arr[i])

    return duplicates

# Test
arr = [4, 3, 2, 7, 8, 2, 3, 1]
print(find_duplicates_sort(arr))  # Output: [2, 3]


[2, 3]
